// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCJ2Ytt8_WZG3XQLRnVCcmHx4K743hFLz0',
    appId: '1:18383484120:web:cae83f9c269a2188be53ad',
    messagingSenderId: '18383484120',
    projectId: 'saathiapp-b1d7e',
    authDomain: 'saathiapp-b1d7e.firebaseapp.com',
    storageBucket: 'saathiapp-b1d7e.appspot.com',
    measurementId: 'G-CMSNZ6NB6M',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBXJ6OHW-7M68M6Mdr4jo46VoAQFkAGglo',
    appId: '1:18383484120:android:3eebb7eb58024e09be53ad',
    messagingSenderId: '18383484120',
    projectId: 'saathiapp-b1d7e',
    storageBucket: 'saathiapp-b1d7e.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB9bO6OU27hGosqMdRcH6wiQVyQCKiuEE4',
    appId: '1:18383484120:ios:65775277c08283fdbe53ad',
    messagingSenderId: '18383484120',
    projectId: 'saathiapp-b1d7e',
    storageBucket: 'saathiapp-b1d7e.appspot.com',
    iosClientId: '18383484120-8qlgrs431cpth9mh5htitk8pa1i3cm13.apps.googleusercontent.com',
    iosBundleId: 'com.example.saathi',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB9bO6OU27hGosqMdRcH6wiQVyQCKiuEE4',
    appId: '1:18383484120:ios:65775277c08283fdbe53ad',
    messagingSenderId: '18383484120',
    projectId: 'saathiapp-b1d7e',
    storageBucket: 'saathiapp-b1d7e.appspot.com',
    iosClientId: '18383484120-8qlgrs431cpth9mh5htitk8pa1i3cm13.apps.googleusercontent.com',
    iosBundleId: 'com.example.saathi',
  );
}
